### ISSUE TITLE
need help in counting divisors

### ISSUE THREAD

**Issue by pritam047** [Hackodex-ITER/CSES-Problems#52]
time limit exceeds for this problem...check python->pritam047->pritam047_counting_divisors.py

**Comment by belikesayantan** [comment]
@pritam047, there is a formula that if a number `n` can be written as `n = A^x * B^y * C^z` where A, B, C, ... are prime numbers and x, y, z are positive integers, then  number of distinct divisors can be = `(x + 1) * (y + 1) * (z + 1)`. 

now, in the given problem finding prime divisors in O(n^1/2) might exceed time limit, so try [Sieve Of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes) Algorithm for this.

**Comment by pritam047** [comment]
@kartavyashankar it's given in the question..the link to the problem is provided in comments

**Comment by pritam047** [comment]
@belikesayantan thanks..will try it out

**Comment by pritam047** [comment]
Thanks,Sieve of Eratosthenes helped!
